# fly.toml app configuration file generated for remote-googlemap-mcp on 2025-06-10T13:20:19+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'brave-search'
primary_region = 'cdg'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb '
  cpu_kind = 'shared'
  cpus = 1

[env]
  SERVICE='brave-search'
